version: 2.1

orbs:
  docker: circleci/docker@2.1.4

jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.24   # Enables Docker commands in CircleCI
      - run:
          name: Build Docker Image
          command: docker build -t fatb0y13-Adrian/flask-docker-app-for-devops:latest .

  publish:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.24   # Enables Docker commands in CircleCI
      - run:
          name: Login to Docker Hub
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login --username "$DOCKERHUB_USERNAME" --password-stdin
      - run:
          name: Push Docker Image
          command: |
            echo "Push Docker image..."
            docker push fatb0y13-Adrian/flask-docker-app-for-devops:latest

workflows:
  version: 2
  build-and-push:
    jobs:
      - build
      - publish:
          requires:
            - build