version: 2.1

orbs:
  docker: circleci/docker@2.1.4

jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.24   # Enables Docker commands in CircleCI
      - run:
          name: Build Docker Image
          command: docker build -t education-space/flask-docker-app-for-devops:latest .

  test:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: pip install -r requirements.txt
      - run:
          name: Run Tests
          command: pytest  # Replace with your actual test command

  publish:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.24   # Enables Docker commands in CircleCI
      - run:
          name: Build Docker Image
          command: docker build -t education-space/flask-docker-app-for-devops:latest .
      - run:
          name: Login to Docker Hub
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login --username "$DOCKERHUB_USERNAME" --password-stdin
      - run:
          name: Push Docker Image
          command: |
            echo "Pushing Docker image to Docker Hub..."
            docker push education-space/flask-docker-app-for-devops:latest

workflows:
  version: 2
  build-and-push:
    jobs:
      - build
      - test:
          requires:
            - build
      - publish:
          requires:
            - test