version: 2.1

orbs:
  docker: circleci/docker@2.1.4

jobs:
  build-and-push:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.24
      - docker/check
      - docker/build:
          image: fatb0y13/flask-docker-app-for-devops
          tag: latest
      - docker/push:
          image: fatb0y13/flask-docker-app-for-devops
          tag: latest

workflows:
  simple_workflow:
    jobs:
      - build-and-push